//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by C:\projects\bo2k\bo2kgui\bo2kgui.rc
//
#define IDC_INSERT                      3
#define IDC_REMOVE                      4
#define IDD_ABOUTBOX                    100
#define IDC_TASKBAR                     112
#define IDR_MAINFRAME                   128
#define IDR_BOWKSPTYPE                  129
#define IDB_DLGBTNIMAGES                130
#define IDD_SERVERLIST                  131
#define IDI_BOCOMPUTER                  132
#define IDD_NEWMACHINEDLG               133
#define IDB_LITTLE_BOCOMPS              133
#define IDB_NORMAL_BOCOMPS              134
#define IDI_NEWMACHINE                  135
#define IDD_BOSERVERDLG                 135
#define IDI_DELETEMACHINE               136
#define IDR_SERVERMENU                  145
#define IDR_SERVERLISTMENU              146
#define IDB_CMDTREE_IMAGELIST           153
#define IDB_CDCBANNER1                  155
#define IDI_EDITMACHINE                 156
#define IDD_QUERYDLG                    157
#define IDB_BO2K                        158
#define IDD_PLUGINS                     160
#define IDB_IMGLIST                     162
#define IDI_SVRLIST                     163
#define IDB_VECTORBALL                  165
#define IDB_VECTORMASK                  166
#define IDI_VECTORBALL                  167
#define IDD_INTERACTIVE_CONNECT         170
#define IDD_INTERACTIVE_LISTEN          171
#define IDI_CONNECTICON                 172
#define IDD_COMCTLDLG                   175
#define IDR_GRADIENTMENU                177
#define IDR_BKGNDPOPUP                  178
#define IDR_TRAYICON                    180
#define IDD_SPLASH                      181
#define IDB_SPLASH                      182
#define IDC_STR_CURRENTVALUE            1006
#define IDC_STR_NEWVALUE                1007
#define IDC_SETVALUE                    1008
#define IDC_STATIC1                     1011
#define IDC_STATIC2                     1012
#define IDC_STATIC_CURVAL               1013
#define IDC_STATIC_NEWVAL               1014
#define IDC_PLUGINS                     1015
#define IDC_OPTIONVARIABLES             1019
#define IDC_BOOL_DISABLED               1022
#define IDC_BOOL_ENABLED                1023
#define IDC_BOOL_GROUP                  1024
#define IDC_SERVER_ADDRESS              2001
#define IDC_CONNECTION_TYPE             2002
#define IDC_ENCRYPTION_ENGINE           2003
#define IDC_AUTHENTICATION_PROCESS      2004
#define IDC_AUTH_HANDLER                2004
#define IDC_MACHINENAME                 2005
#define IDC_OPT3                        2019
#define IDC_OPT2                        2021
#define IDC_STATIC_OPT3                 2022
#define IDC_STATIC_OPT2                 2023
#define IDC_OPT1                        2024
#define IDC_STATIC_OPT1                 2025
#define IDC_SERVERRESPONSE              2026
#define IDC_SENDCOMMAND                 2028
#define IDC_TREE2                       2034
#define IDC_SERVERCOMMANDS              2034
#define IDC_PLUGINLIST                  2038
#define IDC_ACTIVATEPLUGIN              2039
#define IDC_MACHINEINFO                 2041
#define IDC_DOCKING                     2042
#define IDC_QUERYONCONNECT              2043
#define IDC_GRADIENT                    2044
#define IDC_CONNECTCHECK                2046
#define IDC_CLEARRESPONSES              2047
#define IDC_CDC_URL                     2048
#define IDC_L0PHT_URL                   2049
#define IDC_STATIC_SUPPORTEDPLUGINS     2050
#define IDC_STATIC_SERVERRESPONSE       2051
#define IDC_STATIC_SERVERCOMMANDS       2052
#define IDC_SETTINGS                    2058
#define IDC_COMPILETIME                 2059
#define IDC_IEUPDATE                    2060
#define IDC_COMCTLUPD                   2061
#define IDC_SPLASH                      2063
#define IDS_HIDE                        5000
#define IDS_EXPAND                      5001
#define IDS_CONTRACT                    5002
#define IDB_BUTTON_IMAGES               5003
#define IDC_TABCTRLBAR                  5003
#define IDB_BTN_EXPLORER                5006
#define IDB_BTN_ARROW                   5012
#define IDC_HSPLITBAR                   30980
#define IDC_VSPLITBAR                   30981
#define ID_NEWMACHINE                   32771
#define ID_DELETEMACHINE                32772
#define ID_DETAILS                      32773
#define ID_SERVERLIST                   32774
#define ID_EDITMACHINE                  32775
#define IDM_SERVERLIST                  32777
#define IDP_PINGSERVER                  32778
#define ID_REQUERYSERVER                32779
#define IDP_REQUERYSERVER               32780
#define ID_PINGSERVER                   32781
#define IDP_DELETESERVER                32782
#define ID_ACTIVATESERVER               32783
#define ID_INSERTMACHINE                32785
#define IDP_ADDMACHINE                  32786
#define IDP_ADDSERVER                   32787
#define IDM_PLUGINS                     32788
#define IDM_GRADIENTS                   32791
#define IDM_MENUTYPE                    32795
#define ID_SERVER_NEW                   32800
#define ID_SERVER_EDIT                  32801
#define ID_SERVER_DELETE                32802
#define IDM_COLOR_0                     32805
#define IDM_COLOR_1                     32806
#define IDM_COLOR_2                     32807
#define IDM_COLOR_3                     32808
#define IDM_COLOR_RED                   32809
#define IDM_COLOR_GREEN                 32810
#define IDM_COLOR_YELLOW                32811
#define IDM_COLOR_ORANGE                32812
#define IDM_COLOR_VIOLET                32814
#define IDM_COLOR_BROWN                 32815
#define IDM_COLOR_BLUE                  32816
#define ID_BACKGROUNDPOPUPMENU_SOLIDCOLOR 32817
#define IDM_SOLIDCOLOR                  32818
#define IDM_BITMAP                      32819
#define IDM_STRETCHBITMAP               32820
#define IDM_TILE                        32821
#define ID_FILE_NEWSERVER               32823
#define IDM_PLUGIN_0                    40000
#define IDM_PLUGIN_4095                 44095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32833
#define _APS_NEXT_CONTROL_VALUE         2064
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
